files:
  include: src/**/*.scss
rules:
  brace-style:
    - 2
    -
      style: stroustrup
  class-name-format:
    - 2
    -
      convention: ^[A-Z-]+$
      convention-explanation: 'Class must contain only uppercase letters and hyphens'
  indentation:
    - 2
    -
      size: 4
  leading-zero:
    - 2
    -
      include: true
  max-line-length:
    - 2
    -
      length: 120
  no-ids: 2
  no-invalid-hex: 2
  pseudo-element: 2
